### ISSUE TITLE
Facing the following issue

### ISSUE THREAD

**Issue by intisarnaheen** [paul-pias/Face-Recognition#1]
I am facing the following error. I have tried to update the path of the facebank.pth in the utils.py file. Can you suggest any `solution??

arcface loaded
{'data_path': PosixPath('/home/intisar/Documents/arcface/Face-Recognition-master/data/facebank'), 'work_path': PosixPath('work_space'), 'model_path': PosixPath('work_space/models'), 'log_path': PosixPath('work_space/log'), 'save_path': PosixPath('work_space/save'), 'input_size': [112, 112], 'embedding_size': 512, 'use_mobilfacenet': False, 'facebank_path': PosixPath('/home/intisar/Documents/arcface/Face-Recognition-master/data/facebank/facebank'), 'net_depth': 50, 'drop_ratio': 0.6, 'net_mode': 'ir_se', 'device': device(type='cuda', index=0), 'test_transform': Compose(
    ToTensor()
    Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
), 'data_mode': 'emore', 'vgg_folder': PosixPath('/home/intisar/Documents/arcface/Face-Recognition-master/data/facebank/faces_vgg_112x112'), 'ms1m_folder': PosixPath('/home/intisar/Documents/arcface/Face-Recognition-master/data/facebank/faces_ms1m_112x112'), 'emore_folder': PosixPath('/home/intisar/Documents/arcface/Face-Recognition-master/data/facebank/faces_emore'), 'batch_size': 100, 'threshold': 1.5, 'face_limit': 10, 'min_face_size': 35}
ir_se_50 model opened
learner loaded
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from face_verify import faceRec
  File "/home/intisar/Documents/arcface/Face-Recognition-master/face_verify.py", line 39, in <module>
    targets, names = load_facebank(conf)
  File "/home/intisar/Documents/arcface/Face-Recognition-master/utils.py", line 71, in load_facebank
    embeddings = torch.load('/home/intisar/Documents/arcface/Face-Recognition-master/data/facebank/facebank.pth')
  File "/home/intisar/miniconda3/envs/arcface/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/intisar/miniconda3/envs/arcface/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by paul-pias** [comment]
May I know your numpy version?

**Comment by Deepak2405** [comment]
Is the issue solved?? I am facing the same issue

**Comment by zhangyuan1997** [comment]
I am facing the same issue.
